### ISSUE TITLE
Reporte de practica 3 Cajas de Texto Personalizado

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-carlos-chrs#2]
[Reporte_Practica3_TEXTO_PERSONALIZADO_Hernandez_Matra_carlos_Christian.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-carlos-chrs/files/6359194/Reporte_Practica3_TEXTO_PERSONALIZADO_Hernandez_Matra_carlos_Christian.pdf)

**Comment by Edwin38H** [comment]
calf. 18
Faltaron imagenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
